In [1]:
import numpy as np

### 1) Create 2 arrays: one of 10 zeros and another of 10 ones

In [4]:
# code here
zeroes = np.zeros(shape=(10,))
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# don't code here.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# code here
ones = np.ones(shape=(10,))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# don't code here.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 2) Create an array of 5 sevens

In [6]:
# code here
sevens = np.ones(shape=(5,)) * 7
sevens

array([7., 7., 7., 7., 7.])

In [11]:
# don't code here

array([7, 7, 7, 7, 7])

### 3) Create an array of integers from 5 to 20 inclusive

In [8]:
# code here
np.arange(5, 21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
# don't code here

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 4) Create an array which contains all the even integers from 0 to 20 inclusive

In [9]:
# code here
np.arange(0, 11) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
# don't code here

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### 5) Create an identity matrix of 5x5

In [10]:
# code here
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# don't code here

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 6) Use numpy to generate any random number between 0 and 1

In [11]:
# code here
np.random.random(size=(1))

array([0.36547562])

In [21]:
# don't code here

array([0.11238367])

### 7) Use numpy the same random number between 0 and 1 3 times

In [19]:
# code here
np.random.seed(42)
np.random.random(size=(1))

array([0.37454012])

In [17]:
# code here
np.random.seed(42)
np.random.random(size=(1))

array([0.37454012])

In [18]:
# code here
np.random.seed(42)
np.random.random(size=(1))

array([0.37454012])

In [24]:
# don't code here

array([0.417022])

In [25]:
# don't code here

array([0.417022])

In [26]:
# don't code here

array([0.417022])

### 8)  Create 10 random numbers from a standard normal distribution

In [20]:
# code here
np.random.normal(size=(10,))

array([-1.11188012,  0.31890218,  0.27904129,  1.01051528, -0.58087813,
       -0.52516981, -0.57138017, -0.92408284, -2.61254901,  0.95036968])

In [29]:
# don't code here

array([-0.80217284, -0.44887781, -1.10593508, -1.65451545, -2.3634686 ,
        1.13534535, -1.01701414,  0.63736181, -0.85990661,  1.77260763])

### 9) Create the following matrix and assign it to a variable 

In [32]:
# don't code here

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [23]:
# code here
mat = np.arange(0, 1, step=0.01).reshape(10, 10)
mat

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

### 10) index the last array to see the following results.

In [36]:
# DON'T CODE HERE!

array([[0.55, 0.56],
       [0.65, 0.66]])

In [25]:
# code here
mat[5:7, 5:7]

array([[0.55, 0.56],
       [0.65, 0.66]])

### 11) index the last array to obtain the following result

In [38]:
# DON'T CODE HERE!

0.01

In [27]:
# code here
mat[0, 1]

0.01

### 12) reshape the last array to obtain the following result

In [40]:
# DON'T CODE HERE!

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [30]:
# code here
mat.reshape(100, )

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

### 13) index and reshape the last array to obtain the following result

In [43]:
# DON'T CODE HERE!

array([[0.  ],
       [0.01],
       [0.02],
       [0.1 ],
       [0.11],
       [0.12],
       [0.2 ],
       [0.21],
       [0.22]])

In [37]:
# code here
mat[0:3, 0:3].reshape(9, 1)

array([[0.  ],
       [0.01],
       [0.02],
       [0.1 ],
       [0.11],
       [0.12],
       [0.2 ],
       [0.21],
       [0.22]])

### 14) obtain the following statistics of the last array

In [45]:
# DON'T CODE HERE! 
# mean

0.49499999999999994

In [38]:
# code here 
# mean
mat.mean()

0.49499999999999994

In [46]:
# DON'T CODE HERE! 
# standard deviation

0.2886607004772212

In [39]:
# code here 
# standard deviation
mat.std()

0.2886607004772212

In [47]:
# DON'T CODE HERE!
# minimum value

0.0

In [40]:
# code here
# minimum value
mat.min()

0.0

In [49]:
# DON'T CODE HERE!
# maximum value

0.99

In [41]:
# code here
# maximum value
mat.max()

0.99

In [50]:
# DON'T CODE HERE! 
# median

0.495

In [43]:
# code here
# median
np.median(mat)

0.495

### 15) Re-asign the order of the array dimensions as follows

In [45]:
# from this
array = np.ones((2,64,12))
array.shape

(2, 64, 12)

In [53]:
# DON'T CODE HERE
# to this
array.shape

(12, 2, 64)

In [52]:
# code here
array = array.reshape(12, 2, 64)
array.shape

(12, 2, 64)