In [2]:
import numpy as np
import torch 

### 1) Set numpy and torch seeds to 1

In [4]:
# code here
np.random.seed(1)
torch.random.seed = 1

### 2) Create and assign to a variable a numpy array called 'array' with 10 integer elements starting from 0

In [7]:
# don't code here

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# code here
array = np.arange(0, 10, dtype=int)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3) Convert the last array variable to a pytorch tensor. Assign it to a new variable called 'tensor'.

In [10]:
# don't code here

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [39]:
# code here
tensor = torch.tensor(array, dtype=torch.int32)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

### 4) Convert tensor type from int32 to float32

In [14]:
# don't code here

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
# code here
tensor = tensor.type(dtype=torch.float32)
tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 5) Convert tensor type to LongTensor, equivalent to int64

In [20]:
# don't code here

torch.int64

In [41]:
# code here
tensor = tensor.type(torch.int64)
tensor.dtype

torch.int64

### 6) Reshape tensor as a 2x5 and 5x2 tensors

In [24]:
# don't code here

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
# code here
tensor.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# don't code here

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [43]:
# code here
tensor.reshape(5, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

### 7) Square the tensor values

In [28]:
# don't code here

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=torch.int32)

In [44]:
# code here
tensor ** 2

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### 8) Create a 3-D torch tensor and then move the order of the dimensions. Assign the tensor a variable called 'tensor_3d'. Note: it can have any number of elements on each dimension and any values inside it.

In [38]:
# Don't code here, example

torch.Size([2, 64, 12])

In [44]:
# Don't code here, example

torch.Size([12, 2, 64])

In [58]:
# code here
tensor_3d = torch.ones(size=(2, 64, 12))
tensor_3d.shape

torch.Size([2, 64, 12])

In [59]:
# code here
tensor_3d = tensor_3d.reshape(12, 2, 64)
tensor_3d.shape

torch.Size([12, 2, 64])

### 9) Create a second 3-d tensor with the same shape as your last tensor_3d. It can contain any values inside it. Assign it to a variable called 'second_tensor_3d'

In [76]:
# don't code here 

torch.Size([12, 2, 64])

In [60]:
# code here
second_tensor_3d = torch.empty_like(tensor_3d)
second_tensor_3d.shape

torch.Size([12, 2, 64])

### 10) Apply the following operations between 'tensor_3d' and 'second_tensor_3d'

In [62]:
# code here
# sum them
(tensor_3d + second_tensor_3d).shape

torch.Size([12, 2, 64])

In [63]:
# code here
# substract them
(tensor_3d - second_tensor_3d).shape

torch.Size([12, 2, 64])

In [79]:
# don't code here
# concatenate on the first dimension and print its shape

torch.Size([24, 2, 64])

In [65]:
# code here
torch.concat((tensor_3d, second_tensor_3d), dim=0).shape

torch.Size([24, 2, 64])

In [80]:
# don't code here
# concatenate on the second dimension and print its shape

torch.Size([12, 4, 64])

In [66]:
# code here
torch.concat((tensor_3d, second_tensor_3d), dim=1).shape

torch.Size([12, 4, 64])

In [87]:
# don't code here
# concatenate on the third dimension and print its shape

torch.Size([12, 2, 128])

In [67]:
# code here
torch.concat((tensor_3d, second_tensor_3d), dim=-1).shape

torch.Size([12, 2, 128])

In [95]:
# don't code herecode here
# stack them on a new first dimension and print its shape

torch.Size([2, 12, 2, 64])

In [69]:
# code here
torch.stack((tensor_3d, second_tensor_3d)).shape

torch.Size([2, 12, 2, 64])

### 11) Create a 3-D tensor and apply the following operations. Make sure the number of elements on each dimension are evens. Call it 'tensor'.

In [98]:
# don't code here
# create tensor

torch.Size([2, 4, 6])

In [2]:
# code here
import torch
tensor = torch.ones((2, 4, 6))
tensor.shape

torch.Size([2, 4, 6])

In [106]:
# don't code here
# split the tensor on 2 at the first dimension. stack the result. print shape

torch.Size([2, 1, 4, 6])

In [4]:
# code here
torch.stack((tensor[0, None,  ::, ::], tensor[1, None, ::, ::])).shape

torch.Size([2, 1, 4, 6])

In [107]:
# code here
# split the tensor on 2 at the third dimension. stack the result. print shape

torch.Size([4, 2, 1, 6])

In [7]:
# code here
print(tensor[::, 2:, ::].shape)
torch.stack((tensor[::, 0:2:, ::], tensor[::, 2:, ::])).shape

torch.Size([2, 2, 6])


torch.Size([2, 2, 2, 6])

In [109]:
# code here
# add a 4th dimension and print the shape. stack the result. print shape

torch.Size([6, 2, 4, 1])

In [8]:
# code here
tensor = tensor[::, ::, ::, None]
print(tensor.shape)
torch.stack((tensor, tensor)).shape

torch.Size([2, 4, 6, 1])


torch.Size([2, 2, 4, 6, 1])

In [89]:
# don't code here
# additional: 
# convert any tensor to a numpy array
tensor.numpy()

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]], dtype=float32)

### 12) Create with torch directly 2 1-D tensors, both with different shapes but that both can be matrix-multiplied. Call them 'a' and 'b'. They can contain any elements inside.

In [98]:
# code 'a' here
a = torch.rand((4, 1))
a

tensor([[0.5919],
        [0.9437],
        [0.1362],
        [0.9908]])

In [99]:
# code 'b' here
b = torch.rand((8, 1))
b

tensor([[0.6048],
        [0.4253],
        [0.5036],
        [0.4045],
        [0.5039],
        [0.8822],
        [0.6936],
        [0.5356]])

### 13) Matrix-multiply a and b


In [100]:
# code here
torch.matmul(a, b.T)

tensor([[0.3580, 0.2517, 0.2981, 0.2394, 0.2983, 0.5222, 0.4106, 0.3170],
        [0.5707, 0.4014, 0.4753, 0.3817, 0.4756, 0.8326, 0.6546, 0.5054],
        [0.0824, 0.0579, 0.0686, 0.0551, 0.0687, 0.1202, 0.0945, 0.0730],
        [0.5992, 0.4214, 0.4990, 0.4008, 0.4993, 0.8741, 0.6873, 0.5307]])