In [1]:
import torch

In [22]:
import torch

class CustomConvLayer(torch.nn.Module):

    def __init__(self, kernel_size, kernel=None, bias=None) -> None:
        super().__init__()
        if kernel is None:
            kernel = torch.randn(kernel_size)
        if bias is None:
            bias = torch.randn(1)
        self.kernel = torch.nn.Parameter(kernel)
        self.bias = torch.nn.Parameter(bias)

    def forward(self, x):
        # calculate final dimensions
        k0, k1 = self.kernel.shape
        n = x.shape[0] - k0 + 1
        m = x.shape[1] - k1 + 1
        conv = torch.empty((n, m))
        for i in range(n):
            for j in range(m):
                conv[i, j] = torch.sum(x[i:i+k0, j:j+k1] *  self.kernel) + self.bias
        # no padding so dimensionality decreases
        return conv

In [26]:
from torch.nn.functional import conv2d
bias = torch.empty(1).fill_(1.)
kernel = torch.eye(3)

conv_custom = CustomConvLayer((3, 3), kernel=kernel, bias=bias)
#conv_torch = 

a = torch.randn(5, 5)
r_custom = conv_custom(a)

# unsqueeze because torch expects batch and channel which my implementation ignores
a.unsqueeze_(0)
a.unsqueeze_(0)
kernel.unsqueeze_(0)
kernel.unsqueeze_(0)
r_torch = conv2d(a, weight=kernel, bias=bias)

print(r_custom)
print(r_torch)

tensor([1.])
tensor([[ 1.6316,  3.0112, -0.4925],
        [ 0.9252, -1.7281,  1.9212],
        [ 1.6339,  4.5458,  0.8334]], grad_fn=<CopySlices>)
tensor([[[[ 1.6316,  3.0112, -0.4925],
          [ 0.9252, -1.7281,  1.9212],
          [ 1.6339,  4.5458,  0.8334]]]])
tensor([[[[False, False, False],
          [False,  True, False],
          [ True,  True,  True]]]])


In [27]:
# again but with a random kernel and bias
bias = torch.randn(1)
kernel = torch.randn((3, 3))

conv_custom = CustomConvLayer((3, 3), kernel=kernel, bias=bias)
#conv_torch = 

a = torch.randn(5, 5)
r_custom = conv_custom(a)

# unsqueeze because torch expects batch and channel which my implementation ignores
a.unsqueeze_(0)
a.unsqueeze_(0)
kernel.unsqueeze_(0)
kernel.unsqueeze_(0)
r_torch = conv2d(a, weight=kernel, bias=bias)

print(r_custom)
print(r_torch)

tensor([[ 1.7726,  3.8378, -2.1831],
        [ 3.9326,  0.6296,  0.7809],
        [-0.8454,  1.6290,  3.9339]], grad_fn=<CopySlices>)
tensor([[[[ 1.7726,  3.8378, -2.1831],
          [ 3.9326,  0.6296,  0.7809],
          [-0.8454,  1.6290,  3.9339]]]])
